### ISSUE TITLE
no module named git.exc ?

### ISSUE THREAD

**Issue by pierre3401** [aron-bordin/kivy-designer#164]
I'have a bug when i run main.py:
```python
brp@brp-SVF15N1S2ES:~/kivy-designer$ python main.py > log.txt
[INFO   ] [Logger      ] Record log in /home/brp/.kivy/logs/kivy_15-10-21_1.txt
[INFO   ] Kivy v1.9.0-dev
[INFO   ] [Python      ] v2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2]
[INFO   ] [Factory     ] 172 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil, img_gif (img_sdl2, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: pygame(['text_sdl2'] ignored)
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 10.5.9>
[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Haswell Mobile >
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] virtual keyboard allowed, single mode, docked
[INFO   ] [Clipboard   ] Provider: pygame(['clipboard_sdl2'] ignored)
 Traceback (most recent call last):
   File "main.py", line 2, in <module>
     from designer.app import DesignerApp
   File "/home/brp/kivy-designer/designer/app.py", line 64, in <module>
     from designer.designer_git import DesignerGit
   File "/home/brp/kivy-designer/designer/designer_git.py", line 2, in <module>
     from git.exc import InvalidGitRepositoryError
 ImportError: No module named git.exc
```

**Comment by aron-bordin** [comment]
hi!

please, use the original project repo: https://github.com/kivy/kivy-designer

download it again and update your requirements with:

`pip install -r requirements.txt`
