### ISSUE TITLE
Scroll on UI creator crashs

### ISSUE THREAD

**Issue by aron-bordin** [aron-bordin/kivy-designer#45]
Select a widget and keep using the mouse scroll. 

KD crashes with 

 Traceback (most recent call last):
   File "main.py", line 3, in <module>
     DesignerApp().run()
   File "/usr/lib/python2.7/site-packages/kivy/app.py", line 824, in run
     runTouchApp()
   File "/usr/lib/python2.7/site-packages/kivy/base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 543, in mainloop
     self._mainloop()
   File "/usr/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 300, in _mainloop
     EventLoop.idle()
   File "/usr/lib/python2.7/site-packages/kivy/base.py", line 330, in idle
     self.dispatch_input()
   File "/usr/lib/python2.7/site-packages/kivy/base.py", line 315, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/usr/lib/python2.7/site-packages/kivy/base.py", line 221, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
   File "/usr/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 904, in on_motion
     self.dispatch('on_touch_down', me)
   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
   File "/usr/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 920, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
   File "/home/neo/Programacao/OpenSource/github/kivy-designer/designer/app.py", line 390, in on_touch_down
     return super(FloatLayout, self).on_touch_down(touch)
   File "/usr/lib/python2.7/site-packages/kivy/uix/widget.py", line 382, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
   File "/usr/lib/python2.7/site-packages/kivy/uix/widget.py", line 382, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
   File "/usr/lib/python2.7/site-packages/kivy/uix/widget.py", line 382, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
   File "/usr/lib/python2.7/site-packages/kivy/uix/widget.py", line 382, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
   File "/home/neo/Programacao/OpenSource/github/kivy-designer/designer/ui_creator.py", line 97, in on_touch_down
     return super(UICreator, self).on_touch_down(*args)
   File "/usr/lib/python2.7/site-packages/kivy/uix/widget.py", line 382, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
   File "/usr/lib/python2.7/site-packages/kivy/uix/widget.py", line 382, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
   File "/usr/lib/python2.7/site-packages/kivy/uix/widget.py", line 382, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 699, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7011)
   File "/home/neo/Programacao/OpenSource/github/kivy-designer/designer/playground.py", line 984, in on_touch_down
     App.get_running_app().focus_widget(target)
   File "/home/neo/Programacao/OpenSource/github/kivy-designer/designer/app.py", line 1377, in focus_widget
     self.widget_focused = widget
   File "kivy/properties.pyx", line 397, in kivy.properties.Property.__set__ (kivy/properties.c:4680)
   File "kivy/properties.pyx", line 429, in kivy.properties.Property.set (kivy/properties.c:5203)
   File "kivy/properties.pyx", line 484, in kivy.properties.Property.dispatch (kivy/properties.c:5852)
   File "kivy/_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (kivy/_event.c:12154)
   File "kivy/_event.pyx", line 1074, in kivy._event.EventObservers._dispatch (kivy/_event.c:11451)
   File "kivy/_event.pyx", line 716, in kivy._event.EventDispatcher.__proxy_setter (kivy/_event.c:7605)
   File "kivy/properties.pyx", line 429, in kivy.properties.Property.set (kivy/properties.c:5203)
   File "kivy/properties.pyx", line 484, in kivy.properties.Property.dispatch (kivy/properties.c:5852)
   File "kivy/_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (kivy/_event.c:12154)
   File "kivy/_event.pyx", line 1074, in kivy._event.EventObservers._dispatch (kivy/_event.c:11451)
   File "/home/neo/Programacao/OpenSource/github/kivy-designer/designer/eventviewer.py", line 189, in on_widget
     self.discover(value)
   File "/home/neo/Programacao/OpenSource/github/kivy-designer/designer/eventviewer.py", line 207, in discover
     ip = self.build_for(event)
   File "/home/neo/Programacao/OpenSource/github/kivy-designer/designer/eventviewer.py", line 298, in build_for
     text = self.kv_code_input.get_property_value(self.widget, name)
   File "/home/neo/Programacao/OpenSource/github/kivy-designer/designer/uix/kv_lang_area.py", line 496, in get_property_value
     path_to_widget = self._get_widget_path(widget)
   File "/home/neo/Programacao/OpenSource/github/kivy-designer/designer/uix/kv_lang_area.py", line 97, in _get_widget_path
     tab_panel.tab_list.index(tab_panel.current_tab) - 1
 ValueError: <kivy.uix.tabbedpanel.TabbedPanelItem object at 0x7f7038545940> is not in list

**Comment by aron-bordin** [comment]
probably helps #46

**Comment by aron-bordin** [comment]
fixed, wrong  kv regex
